### ISSUE TITLE
Sequelize as a peer dependency

### ISSUE THREAD

**Issue by visualglitch91** [onhernandes/sequelize-stream#1]
Since this project is meant to be a plugin to sequelize and to be used along side it, I belive it should list sequelize as a peer dependency instead of a dependency, avoind issues like loading two different versions.

https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by onhernandes** [comment]
Nice! This really helps, now I realise that sequelize-model-stream works with Sequelize >= 4! Also, moved sequelize to dev-dep alongside with mysql2 for testing. 

Thanks
